# Generated by Django 5.2.5 on 2025-08-27 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('final_projeto_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='criado_em',
        ),
        migrations.RemoveField(
            model_name='item',
            name='descricao',
        ),
        migrations.AddField(
            model_name='item',
            name='preco',
            field=models.DecimalField(decimal_places=2, default=10.0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='item',
            name='titulo',
            field=models.CharField(max_length=100),
        ),
    ]
